export type VideoReusePayload = {
  modelId?: string;
  prompt: string;
  negativePrompt: string;
  resolution?: string;
  draftMode?: boolean;
  saveAudio?: boolean;
  promptUpsampling?: boolean;
  disableSafetyFilter?: boolean;
  duration: string;
  aspectRatio: string;
  motionIntensity: string;
  cameraMove: string;
  styleStrength: string;
  motionGuidance: number;
  shotType: string;
  fps: string;
  imageUrl?: string;
  endImageUrl?: string;
  referenceImageUrls?: string[];
  audioUrl?: string;
  sourceAssetId?: string;
};

export type VideoGenerationSetup = {
  modelId: string;
  prompt: string;
  negativePrompt: string;
  resolution?: string;
  draftMode?: boolean;
  saveAudio?: boolean;
  promptUpsampling?: boolean;
  disableSafetyFilter?: boolean;
  duration: string;
  aspectRatio: string;
  motionIntensity: string;
  cameraMove: string;
  styleStrength: string;
  motionGuidance: number;
  shotType: string;
  fps: string;
  imageUrl?: string;
  endImageUrl?: string;
  referenceImageUrls?: string[];
  audioUrl?: string;
  sourceAssetId?: string;
};
