export const APP_NAME = "Vireon AI";
export const APP_TAGLINE = "Create stunning AI visuals, motion, video, and sound.";
export const APP_DESCRIPTION =
  "Vireon AI is a next-generation AI creation platform for images, video, motion, and creator publishing.";

export const SEO_KEYWORDS = [
  "Vireon AI",
  "AI image generator",
  "AI video generator",
  "AI image to video",
  "text to image AI",
  "text to video AI",
  "image to video AI",
  "AI art generator",
  "AI photo generator",
  "AI animation generator",
  "AI motion generator",
  "AI creator studio",
  "AI video studio",
  "AI image studio",
  "AI content creation",
  "AI visual generator",
  "AI prompt generator",
  "AI video maker",
  "AI photo editor",
  "AI image editing",
  "AI video editing",
  "AI character generator",
  "AI world builder",
  "AI short video generator",
  "AI cinematic video",
  "AI product video",
  "AI social media content",
  "AI marketing videos",
  "AI fashion photography",
  "AI product photography",
  "ChatGPT image generator",
  "GPT image generator",
  "GPT Image 2",
  "GPT Image 1.5",
  "OpenAI image generation",
  "OpenAI video generation",
  "Kling AI",
  "Kling video generator",
  "Kling 3.0",
  "Kling 3.0 Omni",
  "Kling O1",
  "Runway AI",
  "Runway video generator",
  "Google Veo",
  "Veo 3",
  "Veo video generator",
  "Nano Banana",
  "Nano Banana Pro",
  "Gemini image generator",
  "Flux AI",
  "Flux image generator",
  "Flux Kontext",
  "Flux Pro",
  "Seedance",
  "Seedream",
  "ByteDance AI generator",
  "Wan AI",
  "Wan 2.7",
  "Recraft V4",
  "Recraft AI",
  "Qwen Image",
  "Qwen image generator",
  "Grok Imagine",
  "Imagen 4",
  "OpenArt alternative",
  "Midjourney alternative",
  "Runway alternative",
  "Kling alternative",
  "AI video generation platform",
  "AI image generation platform",
  "best AI image generator",
  "best AI video generator",
  "create AI videos online",
  "create AI images online",
  "generate videos from prompts",
  "generate images from prompts",
  "AI creator tools",
  "AI media library",
  "AI prompt templates",
  "multi scene AI video",
  "AI video projects",
  "AI visual storytelling"
];
